name: Co-Author Approval Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]
  merge_group:

jobs:
  co-author-approval-check:
    if: github.event_name != 'merge_group'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: pinginc/actions/.github/actions/co-author-approval-check@main
