name: Dependency Review

on:
  pull_request:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: pinginc/actions/.github/actions/dependency-review@main
